name: Bug Report
description: Report a bug or issue with Web Terminal
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Execute command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile (Phone)
        - Tablet
        - Other
    validations:
      required: true

  - type: textarea
    id: terminal-commands
    attributes:
      label: Terminal Commands
      description: If applicable, what commands were you running when the issue occurred?
      placeholder: |
        ls -la
        cd /home
        npm install
      render: bash

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: If there are any console errors, please paste them here.
      placeholder: Check browser developer tools (F12) for any error messages.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have provided all the necessary information above
          required: true